apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ecommerce
data:
  PORT: '3000'
  NODEENV: 'production'
  DB_HOST: 'postgres-service'
  DB_PORT: '5432'
  DB_NAME: 'E-Commerce'
  DB_USER: 'postgres'
  DB_SSL: 'false'
  DB_FORCE_SYNC: 'false'
  UPLOAD_STRATEGY: 'azure'
  AZURE_USE_SAS_URLS: 'true'
  AZURE_SAS_EXPIRY_HOURS: '8760'
