#!/bin/bash

# 更新Secret的辅助脚本
echo "更新Kubernetes Secret配置"
echo "请输入实际的配置值，脚本会自动进行base64编码"

read -p "JWT_SECRET: " JWT_SECRET
read -s -p "DB_PASSWORD: " DB_PASSWORD
echo
read -s -p "OPENAI_API_KEY: " OPENAI_API_KEY
echo
read -s -p "GEMINI_API_KEY: " GEMINI_API_KEY
echo
read -p "MONGODB_URI: " MONGODB_URI
read -p "AZURE_STORAGE_ACCOUNT_NAME: " AZURE_STORAGE_ACCOUNT_NAME
read -s -p "AZURE_STORAGE_ACCOUNT_KEY: " AZURE_STORAGE_ACCOUNT_KEY
echo
read -p "AZURE_STORAGE_CONTAINER_NAME: " AZURE_STORAGE_CONTAINER_NAME
read -p "AZURE_STORAGE_CONNECTION_STRING: " AZURE_STORAGE_CONNECTION_STRING

# 生成base64编码的值
JWT_SECRET_B64=$(echo -n "$JWT_SECRET" | base64)
DB_PASSWORD_B64=$(echo -n "$DB_PASSWORD" | base64)
OPENAI_API_KEY_B64=$(echo -n "$OPENAI_API_KEY" | base64)
GEMINI_API_KEY_B64=$(echo -n "$GEMINI_API_KEY" | base64)
MONGODB_URI_B64=$(echo -n "$MONGODB_URI" | base64)
AZURE_STORAGE_ACCOUNT_NAME_B64=$(echo -n "$AZURE_STORAGE_ACCOUNT_NAME" | base64)
AZURE_STORAGE_ACCOUNT_KEY_B64=$(echo -n "$AZURE_STORAGE_ACCOUNT_KEY" | base64)
AZURE_STORAGE_CONTAINER_NAME_B64=$(echo -n "$AZURE_STORAGE_CONTAINER_NAME" | base64)
AZURE_STORAGE_CONNECTION_STRING_B64=$(echo -n "$AZURE_STORAGE_CONNECTION_STRING" | base64)

# 更新secret.yaml文件
cat > secret.yaml << EOF
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ecommerce
type: Opaque
data:
  JWT_SECRET: $JWT_SECRET_B64
  DB_PASSWORD: $DB_PASSWORD_B64
  OPENAI_API_KEY: $OPENAI_API_KEY_B64
  GEMINI_API_KEY: $GEMINI_API_KEY_B64
  MONGODB_URI: $MONGODB_URI_B64
  AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME_B64
  AZURE_STORAGE_ACCOUNT_KEY: $AZURE_STORAGE_ACCOUNT_KEY_B64
  AZURE_STORAGE_CONTAINER_NAME: $AZURE_STORAGE_CONTAINER_NAME_B64
  AZURE_STORAGE_CONNECTION_STRING: $AZURE_STORAGE_CONNECTION_STRING_B64
EOF

echo "secret.yaml已更新！"
echo "现在可以运行: kubectl apply -f secret.yaml"