name: Build and deploy Frontend Azure Web App - ecommerce-react-frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Set environment variables
        run: |
          echo "REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}" >> frontend/.env.production
          echo "REACT_APP_AUTH_TOKEN=${{ vars.REACT_APP_AUTH_TOKEN }}" >> frontend/.env.production

      - name: Build React app
        run: |
          cd frontend
          npm install
          npm run build --if-present
        env:
          DISABLE_ESLINT_PLUGIN: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_13BE8F4B062E4EFCAD7BC1D450E452F4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D597978D96F4F26B35E09E50C89F07B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_094E2928AFF444A58AB3722E2DC77A68 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecommerce-react-frontend'
          slot-name: 'Production'
          package: build
